### ISSUE TITLE
[Site Request] Return channel terminated / removed [youtube.com]

### ISSUE THREAD

**Issue by AplhaSlayer1964** [blackjack4494/yt-dlc#256]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Would it be possible to return a form of notification that a channel has been terminated or deleted in stead of just no videos found on page? I ask because I use youtube-dlc to downlaod multiple channels and another script that sorts out removed videos but would like to be able to do the same with channels, but right now can't tell the difference between termineated / deleted channel and one where they just removed or privated all the videos. Here is an example of an account that has been terminated: https://www.youtube.com/channel/UC9-uPpssy55jrwBVtO_SiDQ
and this is an example of a deleted channel (invalid channel links have the same banner as well):
https://www.youtube.com/channel/UCIcgBZ9hEJxHv6r_jDYOMqg

**Comment by pukkandan** [comment]
@AplhaSlayer1964 I have made a commit to print youtube's error message

**Comment by pukkandan** [comment]
'''bash
$youtube-dl.cmd https://www.youtube.com/channel/UC9-uPpssy55jrwBVtO_SiDQ/
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/home" to the URL
[youtube:tab] UC9-uPpssy55jrwBVtO_SiDQ: Downloading webpage
WARNING: YouTube said: ERROR - This account has been terminated due to multiple or severe violations of YouTube's policy on nudity or sexual content.
ERROR: Unable to recognize tab page; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

$youtube-dl https://www.youtube.com/channel/UCIcgBZ9hEJxHv6r_jDYOMqg
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/home" to the URL
[youtube:tab] UCIcgBZ9hEJxHv6r_jDYOMqg: Downloading webpage
WARNING: YouTube said: ERROR - This channel does not exist.
ERROR: Unable to recognize tab page; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
'''

**Comment by AplhaSlayer1964** [comment]
Awsome! Thank you so much for adding this!
