### ISSUE TITLE
YouTube-DLC_x86: Error loading python35.dll

### ISSUE THREAD

**Issue by Rekrullurker** [blackjack4494/yt-dlc#69]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
Error loading Python DLL 'C:\DOCUME~1\Owner\LOCALS~1\Temp\_MEI33442\python35.dll'.
LoadLibrary: This application has failed to start because the application configuration is incorrect. Reinstalling the application may fix this problem.

## Description

WRITE DESCRIPTION HERE
I know I'm the exception rather than the rule, but I tried to run YouTube-DLC_x86 on my Windows XP system and got the above error. The original YouTube-DL works fine for me, but YouTube-DLC_x86 won't even run because it's looking for a python36.dll, which I don't have.

**Comment by Skibicki** [comment]
The EXE version is not compatible with XP, because it was built with a version of Python past 3.4.
You can use Pip to install yt-dlc.
python -m pip install --upgrade youtube-dlc

If Pip fails, try upgrading to 19.1
python -m pip install --upgrade pip==19.1
If Pip fails to download yt-dlc, then download, and install from the Source zip
python -m pip install yt-dlc.zip
https://github.com/blackjack4494/yt-dlc/releases

### Details:

Install Python 3.4.10. Before installing Python, install Visual C++ 2010 Service Redistributable Package
Python Downloads:
https://www.python.org/downloads/release/python-3410/

Visual C++ Downloads:
https://www.microsoft.com/en-us/download/details.aspx?id=26999
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Python package installation documents:
https://docs.python.org/3.4/installing/index.html

yt-dlc installation:
https://github.com/blackjack4494/yt-dlc#installation

**Comment by blackjack4494** [comment]
I requested python 3.4.10 to be added to `setup-python` some time ago. The binaries are built by github action. I could in theory install a custom version of python. But rather want to wait for them to deploy it.

**Comment by Rekrullurker** [comment]
Thank you for the replies. I was going by the Reddit post that linked here, which said that XP support was included.

Unfortunately, I know absolutely nothing about compiling source code. I've done it exactly twice in my life, both times following detailed step-by-step instructions. Any time I've tried to compile anything else, it hasn't worked.

I looked at the 3.4.10 link above, but all I see are source code downloads and I have no idea what to do with them.

Without step-by-step Windows instructions, I'm lost.

**Comment by Skibicki** [comment]
I forgot some versions don't have official builds. 3.4.4 is the latest here: https://www.python.org/downloads/windows/

**Comment by Skibicki** [comment]
@Rekrullurker Video instructions:
https://www.youtube.com/watch?v=mbWDY2PA_LY
Select "add Python exe to path", when you install.

**Comment by chrisr11** [comment]
How can I make Python embedded into the binary? youtube-dl binary for Windows always had the Python module embedded inside it so it only required Visual C++ 2010 package to be installed separately
